### ISSUE TITLE
Getting error: Unable to perform assignment because the left and right sides have a different number of elements.

### ISSUE THREAD

**Issue by ixtiyoruz** [marccarne/M6project#1]
Hi, thanks for the open-source, however, I have one problem:
I am trying to reproduce your code in python, but I am having a problem with understanding this line:
https://github.com/marccarne/M6project/blob/25c30a3a5cf24142137b61c6bb03eb47b86e1089/lab5/mixtures/my_repmat.m#L43

I run the function alone with a different example:
```
A = ones(1,2,2);A(1,1,2)=2;A(1,2,1)=3;A(1,2,2)=4; 
my_repmat(A, [1,2,2], 4)
```

**Comment by alejandronespereira** [comment]
My Matlab is rusty, but I think it's creating a matrix B of size nelems without assigning any rows or columns, filling in the data from A in the row or column major way MATLAB has and then after it changes the size so the data inside fits well. 
Hope it helps!

**Comment by ixtiyoruz** [comment]
> My Matlab is rusty, but I think it's creating a matrix B of size nelems without assigning any rows or columns, filling in the data from A in the row or column major way MATLAB has and then after it changes the size so the data inside fits well.
> Hope it helps!

Thank you for the response,  yes, I figured that. Furthermore, this little function expects a one-dimensional array, whereas, I am giving it a two dim array, which is not expected by the author I suppose. 
I changed this my_repmat.m Matlab code with this python alternative:

def my_repmat2(A, siz, n):
    return np.tile(A, [siz[0],1])
